name: prana_task4
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  flutter_spinkit: "^4.1.2"
  giffy_dialog: "^1.8.0"
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/harvest.png"
  image_path_ios: "images/harvest.png"
  image_path_android: "images/harvest.png"
  adaptive_icon_background: "images/harvest.png"
  adaptive_icon_foreground: "images/harvest.png"
  
flutter:
  uses-material-design: true

  assets:
    - images/